---
title: Solar system
hero_image: images/banner.png
description: Get to know Python dictionaries by creating a model of the solar system
meta_title: Python coding projects for kids and teens | Solar system
meta_description: Get to know Python dictionaries by creating a model of the solar system!
version: 4
listed: false
copyedit: true
last_tested: "2021-10-13"
landing: true
steps:
  - title: Show Mercury orbit
  - title: Draw Mercury
    completion:
    - engaged
  - title: Add Mercury facts
  - title: Add Venus
    completion:
    - internal
  - title: Add Venus facts
  - title: Add Earth
  - title: Add Earth facts
    completion:
    - external
  - title: "Challenge: Upgrade your project"
    challenge: true
